homework 03
aspdaspn/c_basics pull request #1
Opened 2020-10-03 21:00 UTC by aspdaspn

2020-10-04 09:36 UTC, PavelMeld commented on 03/main.c
> +		scanf("%d", (arr + i++));
Выражения вида `x + y++` обычно стараются разбивать, чтобы не возникало неопределенности порядка выполнения операций.
Тем более `i` - это переменная по которой организован цикл, очень удобно, когда её изменение происходит в явном виде (отдельноф строкой), а не в составе какого-то выражения.
```suggestion
		scanf("%d", arr + i));
		i++;
```

2020-10-04 09:38 UTC, PavelMeld commented on 03/main.c
> +void inputUnsignArray(unsigned int *arr, int len) {
Вроде функции `inputArray` и `inputUnsignArray` совпадают?

2020-10-04 09:40 UTC, PavelMeld commented on 03/main.c
> +	if (odd == 0)
```suggestion
	return odd != 0;
```

2020-10-04 09:42 UTC, PavelMeld commented on 03/main.c
> +		return 1;
```suggestion
	return odd != 0;
```

2020-10-04 09:46 UTC, PavelMeld commented on 03/main.c
> +		printf("%3d%s", arr[i++], (i < len - 1) ? "," : "");
Тут тоже можно переделать под цикл For, чтобы убрать лишнюю строку с объявлением `i` и сделать хорошо читаемой работу с ней.
```suggestion
	for (int i = 0; i < len; i++)
		printf("%3d%s", arr[i], (i < len - 1) ? "," : "");
```

2020-10-04 09:48 UTC, PavelMeld commented on 03/main.c
> +	while (i < len)
Тут можно так же цикл переделать.
Обычно `while` используется в циклах, где граничное условие изменяется каким-то "сложным" способом.
Счётные циклы - это обычно `for`

2020-10-04 09:49 UTC, PavelMeld commented on 03/main.c
> +		if (makeEven(digit_array, ARRAY_LENGTH) == 1){
```suggestion
		if (makeEven(digit_array, ARRAY_LENGTH) == 1) {
```

2020-10-04 09:55 UTC, PavelMeld commented on 03/main.c
> +	if (a == 0)
Ну, вот тут я не уверен, что нужно -1 возвращать. Дальше в коде ты считаешь, что если `descr == -1`, то корней нет.
На самом деле у функции `f(x) = a*x + c` (a = 0, b != 0, c !=0) есть корень `x = -c / b`.
Я бы возвращал -1 если `(a == 0) && (b == 0) && (c != 0)`.
Если только `(a == 0)`, то `x = -c / b`
Т.е. в этом месте, где `if (a == 0)` я бы сдалел эту проверку.

2020-10-04 09:56 UTC, PavelMeld requested changes
Вообще очень круто !

2020-10-04 09:56 UTC, PavelMeld commented on 03/main.c
> +	if (a == 0)
Ну, вот тут я не уверен, что нужно -1 возвращать. Дальше в коде ты считаешь, что если `descr == -1`, то корней нет.
На самом деле у функции `f(x) = a*x + c` (a = 0, b != 0, c !=0) есть корень `x = -c / b`.
Я бы возвращал -1 если `(a == 0) && (b == 0) && (c != 0)`.
Если только `(a == 0)`, то `x = -c / b`
Т.е. в этом месте, где `if (a == 0)` я бы сдалел эту проверку.

2020-10-05 06:43 UTC, aspdaspn commented on 03/main.c
> +		return 1;
а вот этот момент я не понял. return же всегда вернёт 1?

2020-10-05 07:03 UTC, aspdaspn commented on 03/main.c
> +void inputUnsignArray(unsigned int *arr, int len) {
они отличаются типом переменной *arr

2020-10-05 07:24 UTC, PavelMeld requested changes

2020-10-05 07:24 UTC, aspdaspn commented on 03/main.c
> +	if (a == 0)
я возвращаю 0, так как у меня корни квадратного уравнения считаются так:
`33       *x2 = (-b - sqrt(d)) / (2 * a);
34     *x1 = (-b + sqrt(d)) / (2 * a);`
проверка деления на 0

функция у меня не `f(x) = a*x + c`, а `ax^2 + bx + c = 0`
по-моему, у меня - верно

2020-10-05 07:34 UTC, aspdaspn commented on 03/main.c
> +		printf("%d%s", arr[i++], (i < len - 1) ? "," : "");
объясни, пожалуйста что означают `(unsigned short)` и ` % (1U<<16)` в данном выводе

2020-10-05 09:16 UTC, aspdaspn commented on 03/main.c
> +		return 1;
кажется понял: если odd != 0 будет true, и функция вернёт 1

2020-10-05 11:04 UTC, PavelMeld commented on 03/main.c
> +	if (a == 0)
`f(x) = a * x ^ 2 + b * x + c`, при `a == 0` превращается в `f(x) = b * x + c`, и  нее могут быть корни (пусть и не через дискриминант).

2020-10-05 16:31 UTC, PavelMeld approved these changes

2020-10-05 16:34 UTC, merged